# Build
- docker build -t udagram-api-feed ./udagram-api-feed
- docker build -t udagram-api-user ./udagram-api-user
- docker build -t udagram-reverseproxy ./udagram-api-reverseproxy
- docker build -t udagram-frontend ./udagram-frontend

# Tagging
- docker tag udagram-api-feed obuadey/udagram-api-feed:v1
- docker tag udagram-api-user obuadey/udagram-api-user:v1
- docker tag udagram-reverseproxy obuadey/udagram-reverseproxy:v1
- docker tag udagram-frontend obuadey/udagram-frontend:v1

# Push
# Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push obuadey/udagram-api-feed:v1
- docker push obuadey/udagram-api-user:v1
- docker push obuadey/udagram-reverseproxy:v1
- docker push obuadey/udagram-frontend:v1