apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: backend-user
  name: backend-user
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend-user
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: backend-user
    spec:
      containers:
        - env:
            - name: AWS_BUCKET
              value: arn:aws:s3:::mfxgh
            - name: AWS_PROFILE
              value: default
            - name: AWS_REGION
              value: us-east-1
            - name: JWT_SECRET
              value: testing
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_HOST
              value: mfxgh.ctro59ddrr4v.us-east-1.rds.amazonaws.com
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_USERNAME
              value: postgres
            - name: URL
              value: http://localhost:8100
          image: obuadey/udagram-api-user:latest
          name: backend-user
          ports:
            - containerPort: 8081
          resources: {}
      restartPolicy: Always
status: {}
