version: "3"
services:
  reverseproxy:
      image: obuadey/udagram-reverseproxy:latest
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend-user
        - backend-feed
  backend-user:
    image: obuadey/udagram-api-user:latest
    ports:
      - "8081:8081"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: mfxgh.ctro59ddrr4v.us-east-1.rds.amazonaws.com 
      POSTGRES_DB: postgres
      AWS_BUCKET: arn:aws:s3:::mfxgh
      AWS_REGION: us-east-1
      AWS_PROFILE: default 
      JWT_SECRET: testing
      URL: http://localhost:8100
  backend-feed:
    image: obuadey/udagram-api-feed:latest
    ports:
      - "8082:8082"
    environment:
      POSTGRES_USERNAME: postgres 
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: mfxgh.ctro59ddrr4v.us-east-1.rds.amazonaws.com
      POSTGRES_DB: postgres
      AWS_BUCKET: arn:aws:s3:::mfxgh
      AWS_REGION: us-east-1
      AWS_PROFILE: default
      JWT_SECRET: testing
      URL: http://localhost:8100
  frontend:
    image: obuadey/udagram-frontend:latest
    ports:
      - "8100:80"