apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-feed
  labels:
    app: udagram-api-feed-app
spec:
  selector:
    matchLabels:
        app: udagram-api-feed-app
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: udagram-api-feed-app
    spec:
      containers:
        - name: udagram-api-feed-app
          image: obuadey/udagram-api-feed:latest
          ports:
            - containerPort: 8082
              protocol: TCP
          imagePullPolicy: Always