apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-reverseproxy
  labels:
    app: udagram-reverseproxy-app
spec:
  selector:
    matchLabels:
        app: udagram-reverseproxy-app
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: udagram-reverseproxy-app
    spec:
      containers:
        - name: udagram-reverseproxy-app
          image: obuadey/udagram-reverseproxy:latest
          resources:
            requests:
              memory: "100Mi"
            limits:
              memory: "200Mi"
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always